-- ============================================================================
-- nutrition_coach_edits_migration.sql
-- Coach add/remove foods on an ASSIGNED plan (client_nutrition_enrollments →
-- nutrition_assignments). Additive: one RPC + privilege grants. No table,
-- RLS, or existing-function changes. Idempotent: safe to run multiple times.
-- NOT APPLIED YET — run in the Supabase SQL Editor after owner approval.
--
-- Design (locked):
--   * Add    → new nutrition_assignment_foods row, original_* = current_* =
--              values at add time, change_type = 'addition',
--              template_food_id = NULL (not from the template). The
--              'addition' tag also exempts the row from regeneration
--              pruning (which deletes only change_type IS NULL rows).
--   * Remove → row kept, change_type = 'removal', current_quantity = 0,
--              current_* zeroed; original_* stays frozen. History remains
--              queryable and the row survives regeneration.
--   * Every edit appends a nutrition_change_log row with
--     source = 'coach_dashboard' (existing CHECK values 'addition' /
--     'removal' are reused — no constraint changes needed).
--   * Edit window: blocked on completed meals and past dates; allowed on
--     future dates and today's still-assigned meals. Skipped meals are
--     editable (coach override). Enrollment must be active.
-- ============================================================================

-- SUPERSEDED by supabase/nutrition_coach_meal_edit_migration.sql, which
-- contains the identical reviewed definition plus grants (production schema
-- references re-verified there). This file is kept for design history only
-- and must NOT be applied separately — doing so would duplicate the
-- function definition.
